package cacheparser

// Commands lists all the functions this cache would support
var Commands = map[string]func(commandKey string, arguments []string) bool{
	"SET":     checkInputValidity,
	"SADD":    checkInputValidity,
	"SETEX":   checkInputValidity,
	"SETNX":   checkInputValidity,
	"ZADD":    checkInputValidity,
	"HSET":    checkInputValidity,
	"LSET":    checkInputValidity,
	"LPUSH":   checkInputValidity,
	"MSET":    checkInputValidity,
	"HMSET":   checkInputValidity,
	"GET":     checkInputValidity,
	"HGET":    checkInputValidity,
	"HKEYS":   checkInputValidity,
	"LPOP":    checkInputValidity,
	"LINDEX":  checkInputValidity,
	"GETSET":  checkInputValidity,
	"HGETALL": checkInputValidity,
	"HLEN":    checkInputValidity,
	"HMGET":   checkInputValidity,
	"PING":    checkInputValidity,
	"HEXISTS": checkInputValidity,
	"EXISTS":  checkInputValidity,
	"LLEN":    checkInputValidity,
	"MGET":    checkInputValidity,
	"STRLEN":  checkInputValidity,
	"ZCARD":   checkInputValidity,
	"KEYS":    checkInputValidity,
}
